import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const neueMontreal = localFont({
  src: [
    {
      path: './fonts/NeueMontreal-Bold.woff2',
      weight: '700',
      style: 'normal'
    },
    {
      path: './fonts/NeueMontreal-Regular.woff2',
      weight: '400',
      style: 'normal'
    },
  ],
  variable: '--font-neue'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ neueMontreal.variable }`}>{children}</body>
    </html>
  );
}
